[package]
name = "esbuild-rs"
version = "0.1.0"
authors = ["GengTeng<me@gteng.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
path = "src/bin/main.rs"
name = "esbd"
